name: Run Tests

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name
  pull_request:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Assuming your project might use submodules

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies (if needed)
        run: bun install

      - name: Run tests
        run: bun test
