name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Calculate new version
        id: version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          
          # Assuming the tag is in 'v<major>.<minor>.<patch>' format
          IFS='.' read -ra VERSION <<< "${latest_tag#v}"
          major=${VERSION[0]}
          minor=${VERSION[1]}
          patch=${VERSION[2]}

          if [ "${{ github.event.inputs.release_type }}" == "major" ]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [ "${{ github.event.inputs.release_type }}" == "minor" ]; then
            minor=$((minor + 1))
            patch=0
          else
            patch=$((patch + 1))
          fi

          new_version="v${major}.${minor}.${patch}"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"
          
  build_and_tag:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      BINARY_NAME: js-maid
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Use this if your project has submodules

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: bun build App.ts --compile --outfile=${{ env.BINARY_NAME }}-${{ matrix.os }}
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.os }}
          path: ./${{ env.BINARY_NAME }}-${{ matrix.os }}

      - name: Tag the repository
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          git tag ${{ needs.prepare.outputs.new_version }}
          git push origin ${{ needs.prepare.outputs.new_version }}
